### ISSUE TITLE
3rd Floppy setting itself as Drive C

### ISSUE THREAD

**Issue by mudmin** [skiselev/monster-fdc#4]
Thanks for an awesome project.  I've confirmed this behavior with someone else who built these cards separately.  Our 3rd floppy drives always try to become the C drive meaning that we can't boot to our hard drive if we have more than 2 floppies in the system.

Is there anything that we can do to prevent this?  A particular DOS version?  DOS 6.22 doesn't seem to do the trick.

Although the documentation says **_It roughtly corresponds to DOS drive letters - drive 0 = A:, drive 1 = B:, drives' letter assignments after drive B: depend on the DOS version. Newer DOS versions, use C: and following letters for hard drive partitions, and place any remaining floppy drives after hard drive letters. For example, on systems with four floppy drives and two HDD partitions, the drives will be assigned as following: A: - floppy drive 0, B: - floppy drive 1, C: - HDD partition 1, D: - HDD partition 2, E: - floppy drive 2, F: - floppy drive 3_**  This isn't what's happening for either of us

**Comment by skiselev** [comment]
Can you please provide more details?
What is the system/motherboard/BIOS?
What is the type of the hard drive controller?

Generally speaking, this should not be happening, as the floppy drives are enumerated separately from hard drives in the BIOS. Floppy are assigned numbers starting from 0, while hard drives are assigned numbers starting from 80h. So technically you could have 128 floppy drives, before their numbers will overlap with the hard drives.
During the boot, BIOS normally will try to boot from drive 0 - the first floppy drive, and drive 80h - the first hard drive. Drive letter assignment is a purely DOS thing. BIOS doesn't know and doesn't care about them. So it is a bit puzzling to me why having 3 floppy drives would prevent system from booting from the HDD

**Comment by mudmin** [comment]
Thanks for taking the time to respond. Gadget Reboot tried on the 286 in his video and got the same issue. 

I tried on a 486 VLB motherboard with a SIS chipset and an award bios
A Socket 7 TL2 Motherboard with an Ami Bios 
A Socket 7 TL3+  Motherboard with Ami Bios
with a Lo-tech XT-IDE XT ISA to IDE CompactFlash Adapter, an XT-IDE that I built myself and an IDE to SD solution on the stock controller.

All of the above appear to try to boot the 3rd floppy drive on the chain (regardless of first/second fdc location) instead of the hard drive. 

I've spent all weekend fiddling with this. I'm open to using a different DOS image, but everything I've tried so far works great until I add that third drive and then that drive tries to boot.

**Comment by GadgetReboot** [comment]
I tried a 286 motherboard Biostar MB- 1 2 1 2 C  with C&T (chips & technologies?) chipset, 
AMI BIOS   POST screen says (c) 1985-1989, and ROM BIOS date 8/30/90

The motherboard has no on board disk or serial/parallel port controllers so for a HDD I'm using a Glitchwrks XT-IDE 4 card and plugged into that, the FC1307A-based SD to IDE Adapter (SD35VC0) and a bootable SD card with DOS 6.22, which boots normally with 1 or 2 floppy drives installed.

On the FDC first port of the primary channel, I have a single cable with a 1.2 MB and 1.44 MB drive set in the FDC BIOS as drive 0 and 1, and I can boot into the SD card as drive C.

If I add another floppy cable with a 3rd drive (1.44 MB) on the second header of the primary channel and just add it as the next available drive number 2, now when I boot it tries to boot off that new floppy as drive C.

The same happens if I instead plug that 3rd floppy into the first connector of the secondary floppy channel and set that as drive number 2.  (didn't try the final header on the secondary channel).

**Comment by skiselev** [comment]
In both cases, the problem seems to be the Universal XTIDE BIOS attempting to boot from the third floppy when drive "C" is selected. It is not related to the Monster FDC or Multi-floppy BIOS.
See the discussion at the [VCFed forum](https://forum.vcfed.org/index.php?threads/sergeys-8-bit-fdc-xt-ide.1242098/)
